=== entcore/feeder-aaf/src/main/resources/ficAlimMENESR.dtd
<!ELEMENT ficAlimMENESR (addRequest|modifyRequest|deleteRequest)*>
<!ELEMENT addRequest (operationalAttributes, identifier, attributes)>
<!ELEMENT modifyRequest (operationalAttributes, identifier, modifications)>
<!ELEMENT deleteRequest (operationalAttributes, identifier)>
<!ELEMENT operationalAttributes (attr)> <!-- Pas de controle : l'attribut "name" de l'element "attr" doit etre egal a "categoriePersonne" ou "categorieStructure" -->
<!ELEMENT identifier (id)>
<!ELEMENT attributes (attr+)>
<!ELEMENT attr (value+)>
<!ELEMENT modifications (modification+)>
<!ELEMENT modification (value+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ATTLIST modification
	name CDATA #REQUIRED
	operation (replace) #REQUIRED>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0000.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>1986923</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>1986923</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>LYBLE</value></attr>
<attr name="sn"><value>Nichols</value></attr>
<attr name="givenName"><value>Mélodie</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04100</value></attr>
<attr name="ENTPersonVille"><value>MANOSQUE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2002782</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2002782</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>GSUELJEV</value></attr>
<attr name="sn"><value>Parker</value></attr>
<attr name="givenName"><value>Athéna</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04200</value></attr>
<attr name="ENTPersonVille"><value>SISTERON</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2002783</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2002783</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>HVAEKFYW</value></attr>
<attr name="sn"><value>Parker</value></attr>
<attr name="givenName"><value>Yóu</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04200</value></attr>
<attr name="ENTPersonVille"><value>SISTERON</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2002812</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2002812</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>KSATUET</value></attr>
<attr name="sn"><value>Sims</value></attr>
<attr name="givenName"><value>Maïwenn</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04160</value></attr>
<attr name="ENTPersonVille"><value>CHATEAU ARNOUX ST AUBAN</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2002813</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2002813</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>FZEVIEZ</value></attr>
<attr name="sn"><value>Sims</value></attr>
<attr name="givenName"><value>Marie-josée</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04160</value></attr>
<attr name="ENTPersonVille"><value>CHATEAU ARNOUX ST AUBAN</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2002828</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2002828</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>SMEJDEQ</value></attr>
<attr name="sn"><value>Carter</value></attr>
<attr name="givenName"><value>Uò</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04200</value></attr>
<attr name="ENTPersonVille"><value>SISTERON</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2002829</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2002829</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>QOAJ</value></attr>
<attr name="sn"><value>Carter</value></attr>
<attr name="givenName"><value>Åslög</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04200</value></attr>
<attr name="ENTPersonVille"><value>SISTERON</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2003407</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2003407</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>TYGAEZ</value></attr>
<attr name="sn"><value>Murray</value></attr>
<attr name="givenName"><value>Åke</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>84290</value></attr>
<attr name="ENTPersonVille"><value>STE CECILE LES VIGNES</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>
