=== entcore/feeder-aaf/src/main/resources/ficAlimMENESR.dtd
<!ELEMENT ficAlimMENESR (addRequest|modifyRequest|deleteRequest)*>
<!ELEMENT addRequest (operationalAttributes, identifier, attributes)>
<!ELEMENT modifyRequest (operationalAttributes, identifier, modifications)>
<!ELEMENT deleteRequest (operationalAttributes, identifier)>
<!ELEMENT operationalAttributes (attr)> <!-- Pas de controle : l'attribut "name" de l'element "attr" doit etre egal a "categoriePersonne" ou "categorieStructure" -->
<!ELEMENT identifier (id)>
<!ELEMENT attributes (attr+)>
<!ELEMENT attr (value+)>
<!ELEMENT modifications (modification+)>
<!ELEMENT modification (value+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ATTLIST modification
	name CDATA #REQUIRED
	operation (replace) #REQUIRED>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0002.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2033187</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2033187</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>SIOQ</value></attr>
<attr name="sn"><value>Thompson</value></attr>
<attr name="givenName"><value>Sélène</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13110</value></attr>
<attr name="ENTPersonVille"><value>PORT DE BOUC</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0011.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2309527</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2309527</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>KTAKA</value></attr>
<attr name="sn"><value>Henderson</value></attr>
<attr name="givenName"><value>Cunégonde</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04130</value></attr>
<attr name="ENTPersonVille"><value>VOLX</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2311586</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2311586</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>LYQTUQJH</value></attr>
<attr name="sn"><value>Little</value></attr>
<attr name="givenName"><value>Méthode</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13140</value></attr>
<attr name="ENTPersonVille"><value>MIRAMAS</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2314801</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2314801</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>HYBPFIDJJAM</value></attr>
<attr name="sn"><value>Griffin</value></attr>
<attr name="givenName"><value>Géraldine</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13600</value></attr>
<attr name="ENTPersonVille"><value>LA CIOTAT</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2318292</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2318292</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>LAICTY</value></attr>
<attr name="sn"><value>Washington</value></attr>
<attr name="givenName"><value>Görel</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>84550</value></attr>
<attr name="ENTPersonVille"><value>MORNAS</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2318302</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2318302</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>XODGID</value></attr>
<attr name="sn"><value>Washington</value></attr>
<attr name="givenName"><value>Yú</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13400</value></attr>
<attr name="ENTPersonVille"><value>AUBAGNE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2318846</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2318846</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>LONUZSQEGFOK</value></attr>
<attr name="sn"><value>Thompson</value></attr>
<attr name="givenName"><value>Eloïse</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13008</value></attr>
<attr name="ENTPersonVille"><value>MARSEILLE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0001.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2004775</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2004775</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>SAKSOL</value></attr>
<attr name="sn"><value>Frazier</value></attr>
<attr name="givenName"><value>Tú</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13510</value></attr>
<attr name="ENTPersonVille"><value>EGUILLES</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2004882</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2004882</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>GOLVE</value></attr>
<attr name="sn"><value>Ray</value></attr>
<attr name="givenName"><value>Léonore</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13090</value></attr>
<attr name="ENTPersonVille"><value>AIX EN PROVENCE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2005363</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2005363</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>GBEPBYAJ</value></attr>
<attr name="sn"><value>Butler</value></attr>
<attr name="givenName"><value>Réjane</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13110</value></attr>
<attr name="ENTPersonVille"><value>PORT DE BOUC</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2005364</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2005364</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>SQADKAEF</value></attr>
<attr name="sn"><value>Butler</value></attr>
<attr name="givenName"><value>Stévina</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13110</value></attr>
<attr name="ENTPersonVille"><value>PORT DE BOUC</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2008374</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2008374</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>LEMPUPSCY</value></attr>
<attr name="sn"><value>Greene</value></attr>
<attr name="givenName"><value>Bérénice</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>05200</value></attr>
<attr name="ENTPersonVille"><value>EMBRUN</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2008375</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2008375</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>TIRHEY</value></attr>
<attr name="sn"><value>Greene</value></attr>
<attr name="givenName"><value>Danièle</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>05200</value></attr>
<attr name="ENTPersonVille"><value>EMBRUN</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0009.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2264943</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2264943</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>VOJOMH</value></attr>
<attr name="sn"><value>Austin</value></attr>
<attr name="givenName"><value>Ma√©na</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>05600</value></attr>
<attr name="ENTPersonVille"><value>GUILLESTRE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>

=== entcore/feeder-aaf/src/test/resources/aaf-test/FULL_ENTTSSERVICES_Complet_20130117_PersEducNat_0001.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->

<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersEducNat</value></attr></operationalAttributes>
<identifier><id>2397809</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2397809</value></attr>
<attr name="ENTPersonDateNaissance"><value>26/04/1978</value></attr>
<attr name="ENTPersonNomPatro"><value>ALBERTO</value></attr>
<attr name="sn"><value>ALBERTO</value></attr>
<attr name="givenName"><value>ALMUDENA</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="mail"><value/></attr>
<attr name="ENTPersonStructRattach"><value>52008</value></attr>
<attr name="ENTAuxEnsCategoDiscipline"><value>17$EDUCATION MUSICALE</value></attr>
<attr name="ENTAuxEnsDisciplinesPoste"><value>EDUCATION MUSICALE$17</value></attr>
<attr name="ENTAuxEnsMEF"><value>50187$1031000F11A$3EME BILANGUE ITALIEN-ANGLAIS</value><value>50187$10310019110$3EME</value><value>50187$1001000B11A$6EME BILANGUE ITALIEN ANGLAIS</value><value>50187$1021000E11A$4EME BILANGUE ITALIEN ANGLAIS</value><value>50187$10010012110$6EME</value><value>50187$10210001110$4EME</value><value>50187$1031000E11A$3EME BILANGUE ALLEMAND-ANGLAIS</value><value>50187$10110001110$5EME</value><value>50187$1011000B11A$5EME BILANGUE ITALIEN ANGLAIS</value></attr>
<attr name="ENTAuxEnsMatiereEnseignEtab"><value>50187$CHANT CHORAL</value><value>50187$EDUCATION MUSICALE</value></attr>
<attr name="ENTAuxEnsClasses"><value>52008$208</value><value>52008$208</value><value>52008$208</value><value>52008$5E1</value><value>52008$213</value><value>52008$213</value><value>52008$208</value><value>52008$1S8</value><value>52008$208</value><value>52008$6E2</value><value>52008$1S8</value><value>52008$1S8</value><value>52008$208</value><value>52008$213</value><value>52008$213</value></attr>
<attr name="ENTAuxEnsGroupes"><value>52008$208</value><value>52008$5E2</value></attr>
<attr name="ENTAuxEnsClassesMatieres"><value>50187$3A$081300</value><value>50187$3B$081300</value><value>50187$3C$081300</value><value>50187$3D$081300</value><value>50187$4A$081300</value><value>50187$4B$081300</value><value>50187$4C$081300</value><value>50187$5A$081300</value><value>50187$5B$081300</value><value>50187$5C$081300</value><value>50187$5D$081300</value><value>50187$6A$081300</value><value>50187$6B$081300</value><value>50187$6C$081300</value><value>50187$6D$081300</value></attr>
<attr name="ENTAuxEnsGroupesMatieres"><value>50187$MCHANKGR$080900</value><value>50187$6IDAUTGD$081300</value></attr>
<attr name="ENTAuxEnsClassesPrincipal"><value/></attr>
<attr name="ENTPersonFonctions"><value>50187$ENS$ENSEIGNEMENT$L1700$EDUCATION MUSICALE</value></attr>
<attr name="PersEducNatPresenceDevantEleves"><value>O</value></attr>
</attributes>
</addRequest>

<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersEducNat</value></attr></operationalAttributes>
<identifier><id>2397810</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2397810</value></attr>
<attr name="ENTPersonDateNaissance"><value>30/09/1961</value></attr>
<attr name="ENTPersonNomPatro"><value>COTREZ</value></attr>
<attr name="sn"><value>DEVAUX</value></attr>
<attr name="givenName"><value>MARIE-CLAUDE</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="mail"><value/></attr>
<attr name="ENTPersonStructRattach"><value>52002</value></attr>
<attr name="ENTAuxEnsCategoDiscipline"><value>00$NON SPECIALISE</value></attr>
<attr name="ENTAuxEnsDisciplinesPoste"><value>READAPTATION$00</value></attr>
<attr name="ENTAuxEnsMEF"><value/></attr>
<attr name="ENTAuxEnsMatiereEnseignEtab"><value/></attr>
<attr name="ENTAuxEnsClasses"><value/></attr>
<attr name="ENTAuxEnsGroupes"><value/></attr>
<attr name="ENTAuxEnsClassesMatieres"><value/></attr>
<attr name="ENTAuxEnsGroupesMatieres"><value/></attr>
<attr name="ENTAuxEnsClassesPrincipal"><value/></attr>
<attr name="ENTPersonFonctions"><value>50045$ADA$READAPTATION$R0098$READAPTATION</value></attr>
<attr name="PersEducNatPresenceDevantEleves"><value>N</value></attr>
</attributes>
</addRequest>

<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersEducNat</value></attr></operationalAttributes>
<identifier><id>2397811</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2397811</value></attr>
<attr name="ENTPersonDateNaissance"><value>25/06/1976</value></attr>
<attr name="ENTPersonNomPatro"><value>CIBRAY</value></attr>
<attr name="sn"><value>DONIKIAN</value></attr>
<attr name="givenName"><value>HAMIDA</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="mail"><value/></attr>
<attr name="ENTPersonStructRattach"><value>52003</value></attr>
<attr name="ENTAuxEnsCategoDiscipline"><value>13$MATHEMATIQUES</value></attr>
<attr name="ENTAuxEnsDisciplinesPoste"><value>MATHEMATIQUES$13</value></attr>
<attr name="ENTAuxEnsMEF"><value>51098$10210001110$4EME</value><value>51098$10110001110$5EME</value><value>51098$10310019110$3EME</value></attr>
<attr name="ENTAuxEnsMatiereEnseignEtab"><value>51098$MATHEMATIQUES</value></attr>
<attr name="ENTAuxEnsClasses"><value>52003$1L1 GRA</value><value>52003$3 DPB</value><value>52003$1L1 GRA</value><value>52003$5EME6</value><value>52003$1L1 GRA</value><value>52003$1L1 GRA</value></attr>
<attr name="ENTAuxEnsGroupes"><value/></attr>
<attr name="ENTAuxEnsClassesMatieres"><value>51098$402$061300</value><value>51098$403$061300</value><value>51098$502$061300</value><value>51098$504$061300</value><value>51098$305$061300</value><value>51098$405$061300</value></attr>
<attr name="ENTAuxEnsGroupesMatieres"><value/></attr>
<attr name="ENTAuxEnsClassesPrincipal"><value/></attr>
<attr name="ENTPersonFonctions"><value>51098$ENS$ENSEIGNEMENT$L1300$MATHEMATIQUES</value></attr>
<attr name="PersEducNatPresenceDevantEleves"><value>O</value></attr>
</attributes>
</addRequest>

</ficAlimMENESR>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0003.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2049716</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2049716</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>PATHAY</value></attr>
<attr name="sn"><value>Wells</value></attr>
<attr name="givenName"><value>Desirée</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13100</value></attr>
<attr name="ENTPersonVille"><value>AIX EN PROVENCE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2049880</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2049880</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>FONDEE</value></attr>
<attr name="sn"><value>Wells</value></attr>
<attr name="givenName"><value>Mélinda</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13100</value></attr>
<attr name="ENTPersonVille"><value>AIX EN PROVENCE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>

=== entcore/feeder-aaf/src/test/resources/aaf-test/clean-FULL_ENTTSSERVICES_Complet_20130117_PersRelEleve_0004.xml
<!DOCTYPE ficAlimMENESR SYSTEM "ficAlimMENESR.dtd">
<ficAlimMENESR>
<!-- versionAF="AAF-VE1301" -->
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2064768</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2064768</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>CIVIH</value></attr>
<attr name="sn"><value>Peters</value></attr>
<attr name="givenName"><value>Faîtes</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>04160</value></attr>
<attr name="ENTPersonVille"><value>CHATEAU ARNOUX ST AUBAN</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2064770</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2064770</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>CADZAXPEYTI</value></attr>
<attr name="sn"><value>Peters</value></attr>
<attr name="givenName"><value>Sélène</value></attr>
<attr name="personalTitle"><value/></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>05290</value></attr>
<attr name="ENTPersonVille"><value>VALLOUISE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2068560</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2068560</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>CEZZQIDW</value></attr>
<attr name="sn"><value>Palmer</value></attr>
<attr name="givenName"><value>Daphnée</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13001</value></attr>
<attr name="ENTPersonVille"><value>MARSEILLE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2068561</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2068561</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>WIEBUPIE</value></attr>
<attr name="sn"><value>Palmer</value></attr>
<attr name="givenName"><value>Méng</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13001</value></attr>
<attr name="ENTPersonVille"><value>MARSEILLE</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2069682</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2069682</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>VYVSAUX</value></attr>
<attr name="sn"><value>Moore</value></attr>
<attr name="givenName"><value>Camélia</value></attr>
<attr name="personalTitle"><value>Mme</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13200</value></attr>
<attr name="ENTPersonVille"><value>ARLES</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2069689</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2069689</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>PETBAFO</value></attr>
<attr name="sn"><value>Moore</value></attr>
<attr name="givenName"><value>Yénora</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>13660</value></attr>
<attr name="ENTPersonVille"><value>ORGON</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
<addRequest>
<operationalAttributes><attr name="categoriePersonne"><value>PersRelEleve</value></attr></operationalAttributes>
<identifier><id>2080722</id></identifier>
<attributes>
<attr name="ENTPersonJointure"><value>2080722</value></attr>
<attr name="ENTPersonDateNaissance"><value/></attr>
<attr name="ENTPersonNomPatro"><value>SUAMCAUUU</value></attr>
<attr name="sn"><value>Gibson</value></attr>
<attr name="givenName"><value>Styrbjörn</value></attr>
<attr name="personalTitle"><value>M.</value></attr>
<attr name="homePhone"><value>0000000000</value></attr>
<attr name="telephoneNumber"><value>0000000000</value></attr>
<attr name="ENTPersonAdresse"><value>XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX</value></attr>
<attr name="ENTPersonCodePostal"><value>84300</value></attr>
<attr name="ENTPersonVille"><value>CAVAILLON</value></attr>
<attr name="ENTPersonPays"><value>FRANCE</value></attr>
</attributes>
</addRequest>
</ficAlimMENESR>
